Sprint 14
Ingvar-fesh/Tracker-ios pull request #1
Opened 2023-05-23 16:39 UTC by Ingvar-fesh

2023-05-24 19:33 UTC, ABashkirova requested changes
Я не смогла проверить полностью работу из-за ошибок в рантайме: при создании трекера, приложение падает при попытке установить вьюшки в иерархию, затем при попытке установить констрейнты. Нужно прислать рабочую версию приложения

2023-05-26 19:13 UTC, IBDesignable approved these changes

2023-05-26 19:13 UTC, IBDesignable commented on Tracker/Controllers/HeaderCollectionView.swift
> +    override init(frame: CGRect) {
```suggestion
    }()
    
    override init(frame: CGRect) {
```

2023-05-26 19:13 UTC, IBDesignable commented on Tracker/Controllers/NewTrackerViewController.swift
> +        }
Попробуй убрать, кажется излишне)
```suggestion
        dismiss(animated: true)
```

2023-06-04 08:40 UTC, merged